spring.application.name=mBanking-Api

# CONFIGURE SECURITY
spring.security.user.name=phen
spring.security.user.password=passPhen

# REGISTER DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=mBanking
spring.datasource.password=mBankingP@ssword
spring.datasource.url=jdbc:postgresql://localhost:7777/DB_mBanking

# JPA CONFIGURE
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

