spring.application.name=mBanking-Api

# CONFIGURE SECURITY
#spring.security.user.name=phen
#spring.security.user.password=passPhen

# REGISTER DRIVER
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=mBanking
spring.datasource.password=mBankingP@ssword
spring.datasource.url=jdbc:postgresql://localhost:7777/DB_mBanking

# JPA CONFIGURE
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true


# Mail
spring.mail.username=nobphen11@gmail.com
spring.mail.password=ibbl glet lecu ievz
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

